/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;

/**
 *
 * @author Danish
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardPanel = new javax.swing.JPanel();
        facultyLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();
        progLabel = new javax.swing.JLabel();
        batchLabel = new javax.swing.JLabel();
        stdLabel = new javax.swing.JLabel();
        hostelLabel = new javax.swing.JLabel();
        wardenLabel = new javax.swing.JLabel();
        allotLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboardPanel.setBackground(new java.awt.Color(102, 0, 102));

        facultyLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        facultyLabel.setForeground(new java.awt.Color(240, 240, 240));
        facultyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/faculty_1.png"))); // NOI18N
        facultyLabel.setText("Faculty");
        facultyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facultyLabelMouseClicked(evt);
            }
        });

        deptLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deptLabel.setForeground(new java.awt.Color(240, 240, 240));
        deptLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/department_1.png"))); // NOI18N
        deptLabel.setText("Department");
        deptLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deptLabelMouseClicked(evt);
            }
        });

        progLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        progLabel.setForeground(new java.awt.Color(240, 240, 240));
        progLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/program_1.png"))); // NOI18N
        progLabel.setText("Program");
        progLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progLabelMouseClicked(evt);
            }
        });

        batchLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        batchLabel.setForeground(new java.awt.Color(240, 240, 240));
        batchLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/batch_1.png"))); // NOI18N
        batchLabel.setText("Batch");
        batchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batchLabelMouseClicked(evt);
            }
        });

        stdLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        stdLabel.setForeground(new java.awt.Color(240, 240, 240));
        stdLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/student_1.png"))); // NOI18N
        stdLabel.setText("Student");
        stdLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stdLabelMouseClicked(evt);
            }
        });

        hostelLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        hostelLabel.setForeground(new java.awt.Color(240, 240, 240));
        hostelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hostel_1.png"))); // NOI18N
        hostelLabel.setText("Hostels");
        hostelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hostelLabelMouseClicked(evt);
            }
        });

        wardenLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        wardenLabel.setForeground(new java.awt.Color(240, 240, 240));
        wardenLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/warden_1.png"))); // NOI18N
        wardenLabel.setText("Warden");
        wardenLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wardenLabelMouseClicked(evt);
            }
        });

        allotLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        allotLabel.setForeground(new java.awt.Color(240, 240, 240));
        allotLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/allotment1_1.png"))); // NOI18N
        allotLabel.setText("Allotment");
        allotLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allotLabelMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hostel_front_2.jpg"))); // NOI18N

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allotLabel)
                    .addComponent(deptLabel)
                    .addComponent(facultyLabel)
                    .addComponent(progLabel)
                    .addComponent(batchLabel)
                    .addComponent(stdLabel)
                    .addComponent(hostelLabel)
                    .addComponent(wardenLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(facultyLabel)
                .addGap(31, 31, 31)
                .addComponent(deptLabel)
                .addGap(27, 27, 27)
                .addComponent(progLabel)
                .addGap(32, 32, 32)
                .addComponent(batchLabel)
                .addGap(29, 29, 29)
                .addComponent(stdLabel)
                .addGap(34, 34, 34)
                .addComponent(hostelLabel)
                .addGap(31, 31, 31)
                .addComponent(wardenLabel)
                .addGap(41, 41, 41)
                .addComponent(allotLabel)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(35, 85, 86));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 204));
        jLabel1.setText("HOSTEL MANAGMENT SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(584, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(515, 515, 515))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(dashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facultyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultyLabelMouseClicked
      facultyLabel.setForeground(new Color(120, 90, 40));
      facultyLabel.setOpaque(true);
      
      deptLabel.setBackground(Color.white);
      deptLabel.setForeground(Color.white);
      deptLabel.setOpaque(false);
      
      progLabel.setBackground(Color.white);
      progLabel.setForeground(Color.white);
      progLabel.setOpaque(false);    
      
      batchLabel.setBackground(Color.white);
      batchLabel.setForeground(Color.white);
      batchLabel.setOpaque(false);
      
      stdLabel.setBackground(Color.white);
      stdLabel.setForeground(Color.white);
      stdLabel.setOpaque(false);
      
      hostelLabel.setBackground(Color.white);
      hostelLabel.setForeground(Color.white);
      hostelLabel.setOpaque(false);
      
      wardenLabel.setBackground(Color.white);
      wardenLabel.setForeground(Color.white);
      wardenLabel.setOpaque(false);
      
      allotLabel.setBackground(Color.white);   
      allotLabel.setForeground(Color.white);
      allotLabel.setOpaque(false);     
        
        FacultyPanel facPanel=new FacultyPanel(); 
        //removing panel
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
            //adding panel
            jPanel1.add(facPanel);
            jPanel1.repaint();
            jPanel1.revalidate();
//        FacultyPanel fac=new FacultyPanel();
//        jPanel1.add(fac);
//        fac.setVisible(true);
    }//GEN-LAST:event_facultyLabelMouseClicked

    private void deptLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deptLabelMouseClicked
      facultyLabel.setBackground(Color.white);
      facultyLabel.setForeground(Color.white);
      facultyLabel.setOpaque(false);
      
      
      deptLabel.setForeground(new Color(120, 90, 40));
      deptLabel.setOpaque(true);
      
      progLabel.setBackground(Color.white);
      progLabel.setForeground(Color.white);
      progLabel.setOpaque(false);    
      
      batchLabel.setBackground(Color.white);
      batchLabel.setForeground(Color.white);
      batchLabel.setOpaque(false);
      
      stdLabel.setBackground(Color.white);
      stdLabel.setForeground(Color.white);
      stdLabel.setOpaque(false);
      
      hostelLabel.setBackground(Color.white);
      hostelLabel.setForeground(Color.white);
      hostelLabel.setOpaque(false);
      
      wardenLabel.setBackground(Color.white);
      wardenLabel.setForeground(Color.white);
      wardenLabel.setOpaque(false);
      
      allotLabel.setBackground(Color.white);   
      allotLabel.setForeground(Color.white);
      allotLabel.setOpaque(false);  
        
        DepartmentPanel deptPanel=new DepartmentPanel();
        //removing panel
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
            //adding panel
            jPanel1.add(deptPanel);
            jPanel1.repaint();
            jPanel1.revalidate();
    }//GEN-LAST:event_deptLabelMouseClicked

    private void progLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progLabelMouseClicked
      facultyLabel.setBackground(Color.white);
      facultyLabel.setForeground(Color.white);
      facultyLabel.setOpaque(false);
      
      deptLabel.setBackground(Color.white);
      deptLabel.setForeground(Color.white);
      deptLabel.setOpaque(false);
      
      
      progLabel.setForeground(new Color(120, 90, 40));
      progLabel.setOpaque(true);    
      
      batchLabel.setBackground(Color.white);
      batchLabel.setForeground(Color.white);
      batchLabel.setOpaque(false);
      
      stdLabel.setBackground(Color.white);
      stdLabel.setForeground(Color.white);
      stdLabel.setOpaque(false);
      
      hostelLabel.setBackground(Color.white);
      hostelLabel.setForeground(Color.white);
      hostelLabel.setOpaque(false);
      
      wardenLabel.setBackground(Color.white);
      wardenLabel.setForeground(Color.white);
      wardenLabel.setOpaque(false);
      
      allotLabel.setBackground(Color.white);   
      allotLabel.setForeground(Color.white);
      allotLabel.setOpaque(false);  
        
        ProgramPanel progPanel=new ProgramPanel();
        //removing panel
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
            //adding panel
            jPanel1.add(progPanel);
            jPanel1.repaint();
            jPanel1.revalidate();
    }//GEN-LAST:event_progLabelMouseClicked

    private void batchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batchLabelMouseClicked
      facultyLabel.setBackground(Color.white);
      facultyLabel.setForeground(Color.white);
      facultyLabel.setOpaque(false);
      
      deptLabel.setBackground(Color.white);
      deptLabel.setForeground(Color.white);
      deptLabel.setOpaque(false);
      
      progLabel.setBackground(Color.white);
      progLabel.setForeground(Color.white);
      progLabel.setOpaque(false);    
      
      
      batchLabel.setForeground(new Color(120, 90, 40));
      batchLabel.setOpaque(true);
      
      stdLabel.setBackground(Color.white);
      stdLabel.setForeground(Color.white);
      stdLabel.setOpaque(false);
      
      hostelLabel.setBackground(Color.white);
      hostelLabel.setForeground(Color.white);
      hostelLabel.setOpaque(false);
      
      wardenLabel.setBackground(Color.white);
      wardenLabel.setForeground(Color.white);
      wardenLabel.setOpaque(false);
      
      allotLabel.setBackground(Color.white);   
      allotLabel.setForeground(Color.white);
      allotLabel.setOpaque(false); 
        
        BatchPanel batchPanel=new BatchPanel();
        //removing panel
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
            //adding panel
            jPanel1.add(batchPanel);
            jPanel1.repaint();
            jPanel1.revalidate();
    }//GEN-LAST:event_batchLabelMouseClicked

    private void stdLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stdLabelMouseClicked
      facultyLabel.setBackground(Color.white);
      facultyLabel.setForeground(Color.white);
      facultyLabel.setOpaque(false);
      
      deptLabel.setBackground(Color.white);
      deptLabel.setForeground(Color.white);
      deptLabel.setOpaque(false);
      
      progLabel.setBackground(Color.white);
      progLabel.setForeground(Color.white);
      progLabel.setOpaque(false);    
      
      batchLabel.setBackground(Color.white);
      batchLabel.setForeground(Color.white);
      batchLabel.setOpaque(false);
      
      
      stdLabel.setForeground(new Color(120, 90, 40));
      stdLabel.setOpaque(true);
      
      hostelLabel.setBackground(Color.white);
      hostelLabel.setForeground(Color.white);
      hostelLabel.setOpaque(false);
      
      wardenLabel.setBackground(Color.white);
      wardenLabel.setForeground(Color.white);
      wardenLabel.setOpaque(false);
      
      allotLabel.setBackground(Color.white);   
      allotLabel.setForeground(Color.white);
      allotLabel.setOpaque(false); 
        
        StudentPanel stdPanel=new StudentPanel();
        //removing panel
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
            //adding panel
            jPanel1.add(stdPanel);
            jPanel1.repaint();
            jPanel1.revalidate();
    }//GEN-LAST:event_stdLabelMouseClicked

    private void hostelLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hostelLabelMouseClicked
      facultyLabel.setBackground(Color.white);
      facultyLabel.setForeground(Color.white);
      facultyLabel.setOpaque(false);
      
      deptLabel.setBackground(Color.white);
      deptLabel.setForeground(Color.white);
      deptLabel.setOpaque(false);
      
      progLabel.setBackground(Color.white);
      progLabel.setForeground(Color.white);
      progLabel.setOpaque(false);    
      
      batchLabel.setBackground(Color.white);
      batchLabel.setForeground(Color.white);
      batchLabel.setOpaque(false);
      
      stdLabel.setBackground(Color.white);
      stdLabel.setForeground(Color.white);
      stdLabel.setOpaque(false);
      
     
      hostelLabel.setForeground(new Color(120, 90, 40));
      hostelLabel.setOpaque(true);
      
      wardenLabel.setBackground(Color.white);
      wardenLabel.setForeground(Color.white);
      wardenLabel.setOpaque(false);
      
      allotLabel.setBackground(Color.white);   
      allotLabel.setForeground(Color.white);
      allotLabel.setOpaque(false); 
        
        HostelPane hostelPanel=new HostelPane();
        //removing panel
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
            //adding panel
            jPanel1.add(hostelPanel);
            jPanel1.repaint();
            jPanel1.revalidate();
    }//GEN-LAST:event_hostelLabelMouseClicked

    private void wardenLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wardenLabelMouseClicked
      facultyLabel.setBackground(Color.white);
      facultyLabel.setForeground(Color.white);
      facultyLabel.setOpaque(false);
      
      deptLabel.setBackground(Color.white);
      deptLabel.setForeground(Color.white);
      deptLabel.setOpaque(false);
      
      progLabel.setBackground(Color.white);
      progLabel.setForeground(Color.white);
      progLabel.setOpaque(false);    
      
      batchLabel.setBackground(Color.white);
      batchLabel.setForeground(Color.white);
      batchLabel.setOpaque(false);
      
      stdLabel.setBackground(Color.white);
      stdLabel.setForeground(Color.white);
      stdLabel.setOpaque(false);
      
      hostelLabel.setBackground(Color.white);
      hostelLabel.setForeground(Color.white);
      hostelLabel.setOpaque(false);
      
      
      wardenLabel.setForeground(new Color(120, 90, 40));
      wardenLabel.setOpaque(true);
      
      allotLabel.setBackground(Color.white);   
      allotLabel.setForeground(Color.white);
      allotLabel.setOpaque(false);    
        
        WardenPanel wardenPanel=new WardenPanel();
        //removing panel
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
            //adding panel
            jPanel1.add(wardenPanel);
            jPanel1.repaint();
            jPanel1.revalidate();
    }//GEN-LAST:event_wardenLabelMouseClicked

    private void allotLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allotLabelMouseClicked
      facultyLabel.setBackground(Color.white);  
      facultyLabel.setForeground(Color.white);
      facultyLabel.setOpaque(false);
      
      deptLabel.setBackground(Color.white);
      deptLabel.setForeground(Color.white);
      deptLabel.setOpaque(false);
      
      progLabel.setBackground(Color.white);
      progLabel.setForeground(Color.white);
      progLabel.setOpaque(false);    
      
      batchLabel.setBackground(Color.white);
      batchLabel.setForeground(Color.white);
      batchLabel.setOpaque(false);
      
      stdLabel.setBackground(Color.white);
      stdLabel.setForeground(Color.white);
      stdLabel.setOpaque(false);
      
      hostelLabel.setBackground(Color.white);
      hostelLabel.setForeground(Color.white);
      hostelLabel.setOpaque(false);
      
      wardenLabel.setBackground(Color.white);
      wardenLabel.setForeground(Color.white);
      wardenLabel.setOpaque(false);
      
       
      allotLabel.setForeground(new Color(120, 90, 40));
      allotLabel.setOpaque(true);     
        
        AllotmentPanel allotPanel=new AllotmentPanel();
        //removing panel
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
            //adding panel
            jPanel1.add(allotPanel);
            jPanel1.repaint();
            jPanel1.revalidate();        
    }//GEN-LAST:event_allotLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allotLabel;
    private javax.swing.JLabel batchLabel;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JLabel deptLabel;
    private javax.swing.JLabel facultyLabel;
    private javax.swing.JLabel hostelLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel progLabel;
    private javax.swing.JLabel stdLabel;
    private javax.swing.JLabel wardenLabel;
    // End of variables declaration//GEN-END:variables
}
